[versions]
agp = "9.2.1" # https://developer.android.com/reference/tools/gradle-api
composeMultiplatform = "1.11.1" # https://github.com/JetBrains/compose-multiplatform/releases
detekt = "2.0.0-alpha.6" # https://github.com/detekt/detekt/releases
develocity = "4.5.0"
foojay = "1.0.0"
gradlePublish = "2.1.1"
hotReload = "1.2.0" # https://github.com/JetBrains/compose-hot-reload/releases
java = "21"
kotlinLang = "2.4.10" # https://kotlinlang.org/docs/releases.html#release-details
ksp = "2.3.11" # https://github.com/google/ksp/releases
metro = "1.4.1" # https://github.com/ZacSweers/metro/releases
room = "2.8.4" # https://developer.android.com/jetpack/androidx/releases/room
serialization = "1.11.0" # https://github.com/Kotlin/kotlinx.serialization/releases
truth = "1.4.5"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
compose-compilerGradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlinLang" }
compose-gradlePlugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "composeMultiplatform" }
compose-hotReloadGradlePlugin = { group = "org.jetbrains.compose.hot-reload", name = "hot-reload-gradle-plugin", version.ref = "hotReload" }
detekt-formatting = { group = "dev.detekt", name = "detekt-rules-ktlint-wrapper", version.ref = "detekt" }
detekt-gradlePlugin = { group = "dev.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
develocity-gradlePlugin = {group="com.gradle", name = "develocity-gradle-plugin", version.ref = "develocity"}
foojayResolver-gradlePlugin = { group = "org.gradle.toolchains.foojay-resolver", name = "org.gradle.toolchains.foojay-resolver.gradle.plugin", version.ref = "foojay" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinLang" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "ksp" }
metro-gradlePlugin = { group = "dev.zacsweers.metro", name = "gradle-plugin", version.ref = "metro" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
serialization-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlinLang" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
# This dependency isn't used directly in this project, but the dependency is used in SerializationConfiguration
serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }

[plugins]
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradlePublish" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
