[versions]
androidGradle = "8.7.2"
detekt = "1.23.7"
gradlePublish = "1.3.0"
hilt = "2.52"
java = "17"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.28"
room = "2.7.0-alpha11"
serialization = "1.7.3"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradle" }
compose-gradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
hilt-gradlePlugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
serialization-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "serialization" }

[plugins]
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradlePublish" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
