[versions]
androidGradle = "8.9.0" # https://developer.android.com/reference/tools/gradle-api
compose = "1.7.3" # https://github.com/JetBrains/compose-multiplatform/releases
gradlePublish = "1.3.1"
hilt = "2.55" # https://github.com/google/dagger/releases
kotlin = "2.1.20" # https://kotlinlang.org/docs/releases.html#release-details
ksp = "2.1.10-1.0.31" # https://github.com/google/ksp/releases
# The following should match Versions.kt
detekt = "1.23.8" # https://github.com/detekt/detekt/releases
java = "17"
room = "2.7.0-rc02" # https://developer.android.com/jetpack/androidx/releases/room

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradle" }
compose-gradlePlugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "compose" }
compose-compilerGradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
hilt-gradlePlugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
serialization-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }

[plugins]
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradlePublish" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
