[versions]
agp = "8.10.0" # https://developer.android.com/reference/tools/gradle-api
compose = "1.8.0-beta02" # https://github.com/JetBrains/compose-multiplatform/releases
detekt = "1.23.8" # https://github.com/detekt/detekt/releases
gradlePublish = "1.3.1"
hilt = "2.56.2" # https://github.com/google/dagger/releases
java = "17"
kotlinLang = "2.1.20" # https://kotlinlang.org/docs/releases.html#release-details
ksp = "2.1.20-2.0.0" # https://github.com/google/ksp/releases
room = "2.7.1" # https://developer.android.com/jetpack/androidx/releases/room
serialization = "1.8.1" # https://github.com/Kotlin/kotlinx.serialization/releases

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
compose-gradlePlugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "compose" }
compose-compilerGradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlinLang" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
hilt-gradlePlugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinLang" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
serialization-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlinLang" }
# This dependency isn't used directly in this project, but the dependency is used in SerializationConfiguration
serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }

[plugins]
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradlePublish" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
