[versions]
androidGradle = "8.8.0" # https://developer.android.com/reference/tools/gradle-api
compose = "1.7.3" # https://github.com/JetBrains/compose-multiplatform/releases
detekt = "1.23.7" # https://github.com/detekt/detekt/releases
gradlePublish = "1.3.0"
hilt = "2.55" # https://github.com/google/dagger/releases
kotlin = "2.1.0" # https://kotlinlang.org/docs/releases.html#release-details
ksp = "2.1.0-1.0.29" # https://github.com/google/ksp/releases
ktlintPlugin = "12.1.1" # https://github.com/JLLeitschuh/ktlint-gradle/releases
# The following should match Versions.kt
java = "17"
room = "2.7.0-alpha12" # https://developer.android.com/jetpack/androidx/releases/room
serialization = "1.8.0" # https://github.com/Kotlin/kotlinx.serialization/releases

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradle" }
compose-gradlePlugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "compose" }
compose-compilerGradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
hilt-gradlePlugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "ksp" }
ktlint-gradlePlugin = {group = "org.jlleitschuh.gradle", name = "ktlint-gradle", version.ref = "ktlintPlugin"}
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
serialization-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "serialization" }

[plugins]
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradlePublish" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
