name: Dependabot Helper
on:
  push:
    branches: [ "dependabot/*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Update Readme
        run: ./gradlew generatePluginVersionSource --continue && git add README.md && git commit -m "Update README.md" && git push
